version: '3.8'

services:
  web:
    image: php:7.4-apache
    container_name: my_lamp_web
    ports:
      - '8080:80'
    volumes:
      - ./html:/var/www/html
    networks:
      - lamp_network

  db:
    image: mysql:5.7
    container_name: my_lamp_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: mydatabase
      # MYSQL_USER: user
      # MYSQL_PASSWORD: userpassword
    networks:
      - lamp_network

  adminer:
    image: adminer
    container_name: my_adminer
    ports:
      - '8081:8080'
    networks:
      - lamp_network

networks:
  lamp_network:
    driver: bridge
